services:

  proxy:
    image: nginx:1.27
    ports:
      - 443:443
    volumes:
      - ./nginx/conf-proxy:/etc/nginx/conf.d/
      - ./nginx/certs:/etc/nginx/certs/
    restart: always
    networks:
      - hub-network

  db:
      image: mysql:8
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - MYSQL_DATABASE=hub_vip
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_MULTIPLE_DATABASES=metabase
      ports:
        - "3306:3306"
      volumes:
        - ./database/db_data:/var/lib/mysql
        - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # Script para criar mais bancos
      networks:
        - hub-network

  api:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=hub_vip
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    networks:
      - hub-network

  metabase:
    image: metabase/metabase:v0.53.7.5
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_CONNECTION_URI=mysql://${DB_USER}:${DB_PASSWORD}@db:3306/metabase?useSSL=false
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - hub-network
  
  parser:
    image: node:18
    volumes:
      - /opt/cdrs:/opt/cdrs
    working_dir: /opt/cdrs
    command: ["node", "parser.js"]
    depends_on:
      - db
    restart: "no"
    networks:
      - hub-network

networks:
  hub-network:
    driver: bridge
