services:

  db:
      image: mysql:8
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      ports:
        - "3306:3306"
      volumes:
        - ./database/db_data:/var/lib/mysql
        - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # Script para criar mais bancos

  api:
    build: .
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  # metabase:
  #   image: metabase/metabase:v0.53.7.5
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - MB_DB_TYPE=mysql
  #     - MB_DB_DBNAME=metabase
  #     - MB_DB_USER=${DB_USER}
  #     - MB_DB_PASSWORD=${DB_PASSWORD}
  #     - MB_DB_HOST=${DB_HOST}
  #   depends_on:
  #     - db